export const STEP_LABELS: Record<string, string> = {
  generate: "Generate Structure",
  seed: "Seed Content",
  draft: "Draft Documents",
  "content-fill": "AI Content Fill",
  review: "Review Documents",
  verify: "Verify Quality",
  lock: "Lock Documents",
  "scaffold-app": "Scaffold App",
  "build-plan": "Build Plan",
  "build-exec": "Build Exec",
  build: "Build App",
  test: "Run Tests",
  activate: "Activate Build",
  deploy: "Deploy",
  package: "Package Kit",
  import: "Import Project",
  reconcile: "Reconcile",
  iterate: "Iterate",
  status: "Status Check",
  next: "Next Steps",
  clean: "Clean Artifacts",
  "kit-create": "Create Workspace",
  overhaul: "Overhaul System",
  "docs-check": "Docs Check",
  doctor: "System Doctor",
  init: "Initialize Workspace",
  "validate-templates": "Validate Templates",
  "knowledge-coverage": "Knowledge Coverage",
  "kit-preview": "Kit Preview",
  "kit-validate": "Kit Validate",
};

export function stepLabel(stepId: string): string {
  return STEP_LABELS[stepId] || stepId;
}
