import type { MetricDefinition } from "../../shared/analytics/metric-registry.js";
import type { CardDefinition } from "../../shared/analytics/card-registry.js";

export const METRIC_REGISTRY: MetricDefinition[] = [
  {
    metric_key: "runs.active.count.live",
    metric_version: "1.0.0",
    label: "Active Runs",
    description: "Number of pipeline runs currently executing.",
    domain_id: "run_lifecycle",
    category: "gauge",
    unit: "count",
    value_type: "integer",
    source_event_types: ["run_started", "run_completed", "run_failed", "run_cancelled"],
    required_dimensions: [],
    optional_dimensions: ["environment"],
    supported_windows: ["live"],
    aggregation_method: "latest",
    computation_kind: "snapshot",
    formula_ref: "runs.active.count",
    formula_version: "1.0.0",
    freshness_sla_ms: 5000,
    owner_component: "analytics-runs-aggregator",
    quality_tier: "critical",
    consumer_surfaces: ["overview_dashboard", "analytics_engine", "runs_page"],
    default_window: "live",
    status: "active",
  },
  {
    metric_key: "runs.started.count.24h",
    metric_version: "1.0.0",
    label: "Runs Started",
    description: "Total number of pipeline runs started in the selected window.",
    domain_id: "run_lifecycle",
    category: "count",
    unit: "count",
    value_type: "integer",
    source_event_types: ["run_started"],
    required_dimensions: [],
    optional_dimensions: ["environment"],
    supported_windows: ["24h", "7d", "30d"],
    aggregation_method: "count",
    computation_kind: "direct",
    formula_ref: "runs.started.count",
    formula_version: "1.0.0",
    freshness_sla_ms: 60000,
    owner_component: "analytics-runs-aggregator",
    quality_tier: "high",
    consumer_surfaces: ["analytics_engine", "runs_page"],
    default_window: "24h",
    status: "active",
  },
  {
    metric_key: "runs.completed.count.24h",
    metric_version: "1.0.0",
    label: "Runs Completed",
    description: "Total number of pipeline runs that completed successfully in the selected window.",
    domain_id: "run_lifecycle",
    category: "count",
    unit: "count",
    value_type: "integer",
    source_event_types: ["run_completed"],
    required_dimensions: [],
    optional_dimensions: ["environment"],
    supported_windows: ["24h", "7d", "30d"],
    aggregation_method: "count",
    computation_kind: "direct",
    formula_ref: "runs.completed.count",
    formula_version: "1.0.0",
    freshness_sla_ms: 60000,
    owner_component: "analytics-runs-aggregator",
    quality_tier: "high",
    consumer_surfaces: ["analytics_engine", "runs_page"],
    default_window: "24h",
    status: "active",
  },
  {
    metric_key: "runs.failed.count.24h",
    metric_version: "1.0.0",
    label: "Failed Runs",
    description: "Total number of pipeline runs that failed in the selected window.",
    domain_id: "run_lifecycle",
    category: "count",
    unit: "count",
    value_type: "integer",
    source_event_types: ["run_failed"],
    required_dimensions: [],
    optional_dimensions: ["environment"],
    supported_windows: ["24h", "7d", "30d"],
    aggregation_method: "count",
    computation_kind: "direct",
    formula_ref: "runs.failed.count",
    formula_version: "1.0.0",
    freshness_sla_ms: 60000,
    owner_component: "analytics-runs-aggregator",
    quality_tier: "high",
    consumer_surfaces: ["analytics_engine", "runs_page"],
    default_window: "24h",
    status: "active",
  },
  {
    metric_key: "runs.success.rate.24h",
    metric_version: "1.0.0",
    label: "Run Success Rate",
    description: "Percentage of terminal runs in the selected window whose outcome was completed_successfully rather than failed, cancelled, or blocked.",
    domain_id: "run_lifecycle",
    category: "rate",
    unit: "percent",
    value_type: "number",
    source_event_types: ["run_completed", "run_failed", "run_cancelled"],
    required_dimensions: [],
    optional_dimensions: ["environment"],
    supported_windows: ["24h", "7d", "30d"],
    aggregation_method: "rate",
    computation_kind: "derived",
    formula_ref: "runs.success.rate",
    formula_version: "1.0.0",
    freshness_sla_ms: 60000,
    owner_component: "analytics-runs-aggregator",
    quality_tier: "critical",
    consumer_surfaces: ["overview_dashboard", "analytics_engine", "runs_page"],
    default_window: "24h",
    status: "active",
  },
  {
    metric_key: "runs.blocked.count.live",
    metric_version: "1.0.0",
    label: "Blocked Runs",
    description: "Number of runs currently in a blocked state.",
    domain_id: "run_lifecycle",
    category: "gauge",
    unit: "count",
    value_type: "integer",
    source_event_types: ["run_blocked"],
    required_dimensions: [],
    optional_dimensions: [],
    supported_windows: ["live"],
    aggregation_method: "latest",
    computation_kind: "snapshot",
    formula_ref: "runs.blocked.count",
    formula_version: "1.0.0",
    freshness_sla_ms: 10000,
    owner_component: "analytics-runs-aggregator",
    quality_tier: "high",
    consumer_surfaces: ["analytics_engine"],
    default_window: "live",
    status: "active",
  },
  {
    metric_key: "runs.duration.avg.24h",
    metric_version: "1.0.0",
    label: "Avg Run Duration",
    description: "Average duration of completed pipeline runs in the selected window.",
    domain_id: "run_lifecycle",
    category: "duration",
    unit: "ms",
    value_type: "number",
    source_event_types: ["run_completed"],
    required_dimensions: [],
    optional_dimensions: ["environment"],
    supported_windows: ["24h", "7d"],
    aggregation_method: "avg",
    computation_kind: "derived",
    formula_ref: "runs.duration.avg",
    formula_version: "1.0.0",
    freshness_sla_ms: 300000,
    owner_component: "analytics-runs-aggregator",
    quality_tier: "standard",
    consumer_surfaces: ["analytics_engine"],
    default_window: "24h",
    status: "active",
  },
  {
    metric_key: "stages.failures.count.24h",
    metric_version: "1.0.0",
    label: "Stage Failures",
    description: "Number of stage execution failures in the selected window.",
    domain_id: "stage_execution",
    category: "count",
    unit: "count",
    value_type: "integer",
    source_event_types: ["stage_failed"],
    required_dimensions: [],
    optional_dimensions: ["stage_id", "environment"],
    supported_windows: ["24h", "7d"],
    aggregation_method: "count",
    computation_kind: "direct",
    formula_ref: "stages.failures.count",
    formula_version: "1.0.0",
    freshness_sla_ms: 60000,
    owner_component: "analytics-stages-aggregator",
    quality_tier: "high",
    consumer_surfaces: ["analytics_engine"],
    default_window: "24h",
    status: "active",
  },
  {
    metric_key: "stages.duration.avg.24h",
    metric_version: "1.0.0",
    label: "Avg Stage Duration",
    description: "Average duration of completed stages in the selected window.",
    domain_id: "stage_execution",
    category: "duration",
    unit: "seconds",
    value_type: "number",
    source_event_types: ["stage_completed"],
    required_dimensions: [],
    optional_dimensions: ["stage_id"],
    supported_windows: ["24h", "7d"],
    aggregation_method: "avg",
    computation_kind: "derived",
    formula_ref: "stages.duration.avg",
    formula_version: "1.0.0",
    freshness_sla_ms: 300000,
    owner_component: "analytics-stages-aggregator",
    quality_tier: "standard",
    consumer_surfaces: ["analytics_engine"],
    default_window: "24h",
    status: "active",
  },
  {
    metric_key: "gates.failed.count.24h",
    metric_version: "1.0.0",
    label: "Gate Failures",
    description: "Number of gate evaluation failures in the selected window.",
    domain_id: "gate_evaluation",
    category: "count",
    unit: "count",
    value_type: "integer",
    source_event_types: ["gate_failed"],
    required_dimensions: [],
    optional_dimensions: ["gate_id"],
    supported_windows: ["24h", "7d"],
    aggregation_method: "count",
    computation_kind: "direct",
    formula_ref: "gates.failed.count",
    formula_version: "1.0.0",
    freshness_sla_ms: 60000,
    owner_component: "analytics-gates-aggregator",
    quality_tier: "critical",
    consumer_surfaces: ["overview_dashboard", "analytics_engine"],
    default_window: "24h",
    status: "active",
  },
  {
    metric_key: "artifacts.generated.count.24h",
    metric_version: "1.0.0",
    label: "Artifacts Generated",
    description: "Total artifacts generated in the selected window.",
    domain_id: "artifact_production",
    category: "count",
    unit: "count",
    value_type: "integer",
    source_event_types: ["artifact_generated"],
    required_dimensions: [],
    optional_dimensions: ["artifact_type"],
    supported_windows: ["24h", "7d", "30d"],
    aggregation_method: "count",
    computation_kind: "direct",
    formula_ref: "artifacts.generated.count",
    formula_version: "1.0.0",
    freshness_sla_ms: 300000,
    owner_component: "analytics-artifacts-aggregator",
    quality_tier: "high",
    consumer_surfaces: ["analytics_engine"],
    default_window: "24h",
    status: "active",
  },
  {
    metric_key: "maintenance.executions.count.24h",
    metric_version: "1.0.0",
    label: "Maintenance Executions",
    description: "Number of maintenance task executions in the selected window.",
    domain_id: "maintenance",
    category: "count",
    unit: "count",
    value_type: "integer",
    source_event_types: ["maintenance_mode_completed", "maintenance_mode_started"],
    required_dimensions: [],
    optional_dimensions: ["maintenance_mode_id"],
    supported_windows: ["24h", "7d", "30d"],
    aggregation_method: "count",
    computation_kind: "direct",
    formula_ref: "maintenance.executions.count",
    formula_version: "1.0.0",
    freshness_sla_ms: 300000,
    owner_component: "analytics-maintenance-aggregator",
    quality_tier: "high",
    consumer_surfaces: ["analytics_engine", "maintenance_page"],
    default_window: "24h",
    status: "active",
  },
  {
    metric_key: "system.health.score.live",
    metric_version: "1.0.0",
    label: "System Health",
    description: "Overall system health score based on recent failure rates and service availability.",
    domain_id: "system_runtime",
    category: "score",
    unit: "score",
    value_type: "number",
    source_event_types: ["healthcheck_passed", "healthcheck_failed"],
    required_dimensions: [],
    optional_dimensions: [],
    supported_windows: ["live"],
    aggregation_method: "custom",
    computation_kind: "composite",
    formula_ref: "system.health.score",
    formula_version: "1.0.0",
    freshness_sla_ms: 30000,
    owner_component: "analytics-system-aggregator",
    quality_tier: "critical",
    consumer_surfaces: ["overview_dashboard", "analytics_engine"],
    default_window: "live",
    status: "active",
  },
  {
    metric_key: "verification.pass.rate.24h",
    metric_version: "1.0.0",
    label: "Verification Pass Rate",
    description: "Percentage of verification checks that passed in the selected window.",
    domain_id: "verification",
    category: "rate",
    unit: "percent",
    value_type: "number",
    source_event_types: ["verification_passed", "verification_failed"],
    required_dimensions: [],
    optional_dimensions: [],
    supported_windows: ["24h", "7d", "30d"],
    aggregation_method: "rate",
    computation_kind: "derived",
    formula_ref: "verification.pass.rate",
    formula_version: "1.0.0",
    freshness_sla_ms: 300000,
    owner_component: "analytics-verification-aggregator",
    quality_tier: "high",
    consumer_surfaces: ["analytics_engine"],
    default_window: "24h",
    status: "active",
  },
  {
    metric_key: "cost.tokens.total.24h",
    metric_version: "1.0.0",
    label: "Token Usage",
    description: "Total tokens consumed across all operations in the selected window.",
    domain_id: "cost_resources",
    category: "count",
    unit: "tokens",
    value_type: "integer",
    source_event_types: ["token_usage_recorded"],
    required_dimensions: [],
    optional_dimensions: ["model_id"],
    supported_windows: ["24h", "7d", "30d"],
    aggregation_method: "sum",
    computation_kind: "direct",
    formula_ref: "cost.tokens.total",
    formula_version: "1.0.0",
    freshness_sla_ms: 300000,
    owner_component: "analytics-cost-aggregator",
    quality_tier: "high",
    consumer_surfaces: ["analytics_engine"],
    default_window: "24h",
    status: "active",
  },
];

export const CARD_REGISTRY: CardDefinition[] = [
  {
    card_id: "runs_active_live_card",
    card_version: "1.0.0",
    title: "Active Runs",
    description: "Shows the number of runs currently executing.",
    domain_id: "run_lifecycle",
    category: "stat",
    visualization: "single_value",
    source_kind: "metric",
    metric_key: "runs.active.count.live",
    required_dimensions: [],
    optional_dimensions: ["environment"],
    supported_windows: ["live"],
    default_window: "live",
    refresh_mode: "realtime",
    value_shape: "scalar",
    unit: "count",
    precision: 0,
    drilldown_target: "/runs",
    evidence_mode: "summary",
    stale_behavior: "show_stale_state",
    empty_behavior: "show_zero",
    error_behavior: "show_last_known_value",
    consumer_surfaces: ["overview_dashboard", "analytics_engine"],
    placement_tags: ["hero"],
    quality_tier: "critical",
    status: "active",
  },
  {
    card_id: "runs_success_rate_24h_card",
    card_version: "1.0.0",
    title: "Run Success Rate",
    subtitle: "Last 24 hours",
    description: "Percentage of terminal runs in the last 24 hours whose outcome was success.",
    domain_id: "run_lifecycle",
    category: "stat",
    visualization: "value_with_delta",
    source_kind: "metric",
    metric_key: "runs.success.rate.24h",
    required_dimensions: [],
    optional_dimensions: ["environment"],
    supported_windows: ["24h", "7d", "30d"],
    default_window: "24h",
    refresh_mode: "poll",
    refresh_interval_ms: 60000,
    value_shape: "scalar",
    unit: "percent",
    precision: 1,
    drilldown_target: "/runs",
    evidence_mode: "summary",
    stale_behavior: "show_last_with_warning",
    empty_behavior: "show_not_applicable",
    error_behavior: "show_error_state",
    consumer_surfaces: ["overview_dashboard", "analytics_engine"],
    placement_tags: ["hero"],
    quality_tier: "critical",
    status: "active",
  },
  {
    card_id: "gates_failures_24h_card",
    card_version: "1.0.0",
    title: "Gate Failures",
    subtitle: "Last 24 hours",
    description: "Number of gate evaluation failures in the last 24 hours.",
    domain_id: "gate_evaluation",
    category: "stat",
    visualization: "single_value",
    source_kind: "metric",
    metric_key: "gates.failed.count.24h",
    required_dimensions: [],
    optional_dimensions: ["gate_id"],
    supported_windows: ["24h", "7d"],
    default_window: "24h",
    refresh_mode: "poll",
    refresh_interval_ms: 60000,
    value_shape: "scalar",
    unit: "count",
    precision: 0,
    evidence_mode: "summary",
    stale_behavior: "show_last_with_warning",
    empty_behavior: "show_zero",
    error_behavior: "show_error_state",
    consumer_surfaces: ["overview_dashboard", "analytics_engine"],
    placement_tags: ["hero"],
    quality_tier: "critical",
    status: "active",
  },
  {
    card_id: "system_health_live_card",
    card_version: "1.0.0",
    title: "System Health",
    description: "Overall system health score based on recent failure rates.",
    domain_id: "system_runtime",
    category: "stat",
    visualization: "single_value",
    source_kind: "metric",
    metric_key: "system.health.score.live",
    required_dimensions: [],
    optional_dimensions: [],
    supported_windows: ["live"],
    default_window: "live",
    refresh_mode: "realtime",
    value_shape: "scalar",
    unit: "score",
    precision: 0,
    evidence_mode: "none",
    stale_behavior: "show_stale_state",
    empty_behavior: "show_zero",
    error_behavior: "show_last_known_value",
    consumer_surfaces: ["overview_dashboard", "analytics_engine"],
    placement_tags: ["hero"],
    quality_tier: "critical",
    status: "active",
  },
  {
    card_id: "runs_started_24h_card",
    card_version: "1.0.0",
    title: "Runs Started",
    subtitle: "Last 24 hours",
    description: "Total pipeline runs started in the last 24 hours.",
    domain_id: "run_lifecycle",
    category: "stat",
    visualization: "single_value",
    source_kind: "metric",
    metric_key: "runs.started.count.24h",
    required_dimensions: [],
    optional_dimensions: [],
    supported_windows: ["24h", "7d", "30d"],
    default_window: "24h",
    refresh_mode: "poll",
    refresh_interval_ms: 60000,
    value_shape: "scalar",
    unit: "count",
    precision: 0,
    drilldown_target: "/runs",
    evidence_mode: "none",
    stale_behavior: "show_last_with_warning",
    empty_behavior: "show_zero",
    error_behavior: "show_error_state",
    consumer_surfaces: ["analytics_engine"],
    placement_tags: ["secondary"],
    quality_tier: "high",
    status: "active",
  },
  {
    card_id: "runs_completed_24h_card",
    card_version: "1.0.0",
    title: "Runs Completed",
    subtitle: "Last 24 hours",
    description: "Pipeline runs completed successfully in the last 24 hours.",
    domain_id: "run_lifecycle",
    category: "stat",
    visualization: "single_value",
    source_kind: "metric",
    metric_key: "runs.completed.count.24h",
    required_dimensions: [],
    optional_dimensions: [],
    supported_windows: ["24h", "7d", "30d"],
    default_window: "24h",
    refresh_mode: "poll",
    refresh_interval_ms: 60000,
    value_shape: "scalar",
    unit: "count",
    precision: 0,
    drilldown_target: "/runs",
    evidence_mode: "none",
    stale_behavior: "show_last_with_warning",
    empty_behavior: "show_zero",
    error_behavior: "show_error_state",
    consumer_surfaces: ["analytics_engine"],
    placement_tags: ["secondary"],
    quality_tier: "high",
    status: "active",
  },
  {
    card_id: "runs_failed_24h_card",
    card_version: "1.0.0",
    title: "Failed Runs",
    subtitle: "Last 24 hours",
    description: "Pipeline runs that failed in the last 24 hours.",
    domain_id: "run_lifecycle",
    category: "stat",
    visualization: "single_value",
    source_kind: "metric",
    metric_key: "runs.failed.count.24h",
    required_dimensions: [],
    optional_dimensions: [],
    supported_windows: ["24h", "7d", "30d"],
    default_window: "24h",
    refresh_mode: "poll",
    refresh_interval_ms: 60000,
    value_shape: "scalar",
    unit: "count",
    precision: 0,
    drilldown_target: "/runs",
    evidence_mode: "none",
    stale_behavior: "show_last_with_warning",
    empty_behavior: "show_zero",
    error_behavior: "show_error_state",
    consumer_surfaces: ["analytics_engine"],
    placement_tags: ["secondary"],
    quality_tier: "high",
    status: "active",
  },
  {
    card_id: "runs_duration_avg_24h_card",
    card_version: "1.0.0",
    title: "Avg Run Duration",
    subtitle: "Last 24 hours",
    description: "Average duration of completed pipeline runs in the last 24 hours.",
    domain_id: "run_lifecycle",
    category: "stat",
    visualization: "single_value",
    source_kind: "metric",
    metric_key: "runs.duration.avg.24h",
    required_dimensions: [],
    optional_dimensions: [],
    supported_windows: ["24h", "7d"],
    default_window: "24h",
    refresh_mode: "poll",
    refresh_interval_ms: 300000,
    value_shape: "scalar",
    unit: "ms",
    precision: 0,
    evidence_mode: "none",
    stale_behavior: "show_last_with_warning",
    empty_behavior: "show_not_applicable",
    error_behavior: "show_error_state",
    consumer_surfaces: ["analytics_engine"],
    placement_tags: ["secondary"],
    quality_tier: "standard",
    status: "active",
  },
  {
    card_id: "stages_failures_24h_card",
    card_version: "1.0.0",
    title: "Stage Failures",
    subtitle: "Last 24 hours",
    description: "Number of stage execution failures in the last 24 hours.",
    domain_id: "stage_execution",
    category: "stat",
    visualization: "single_value",
    source_kind: "metric",
    metric_key: "stages.failures.count.24h",
    required_dimensions: [],
    optional_dimensions: ["stage_id"],
    supported_windows: ["24h", "7d"],
    default_window: "24h",
    refresh_mode: "poll",
    refresh_interval_ms: 60000,
    value_shape: "scalar",
    unit: "count",
    precision: 0,
    evidence_mode: "summary",
    stale_behavior: "show_last_with_warning",
    empty_behavior: "show_zero",
    error_behavior: "show_error_state",
    consumer_surfaces: ["analytics_engine"],
    placement_tags: ["secondary"],
    quality_tier: "high",
    status: "active",
  },
  {
    card_id: "stages_duration_avg_24h_card",
    card_version: "1.0.0",
    title: "Avg Stage Duration",
    subtitle: "Last 24 hours",
    description: "Average duration of completed stages in the last 24 hours.",
    domain_id: "stage_execution",
    category: "stat",
    visualization: "single_value",
    source_kind: "metric",
    metric_key: "stages.duration.avg.24h",
    required_dimensions: [],
    optional_dimensions: ["stage_id"],
    supported_windows: ["24h", "7d"],
    default_window: "24h",
    refresh_mode: "poll",
    refresh_interval_ms: 300000,
    value_shape: "scalar",
    unit: "seconds",
    precision: 1,
    evidence_mode: "none",
    stale_behavior: "show_last_with_warning",
    empty_behavior: "show_not_applicable",
    error_behavior: "show_error_state",
    consumer_surfaces: ["analytics_engine"],
    placement_tags: ["secondary"],
    quality_tier: "standard",
    status: "active",
  },
  {
    card_id: "artifacts_generated_24h_card",
    card_version: "1.0.0",
    title: "Artifacts Generated",
    subtitle: "Last 24 hours",
    description: "Total artifacts generated in the last 24 hours.",
    domain_id: "artifact_production",
    category: "stat",
    visualization: "single_value",
    source_kind: "metric",
    metric_key: "artifacts.generated.count.24h",
    required_dimensions: [],
    optional_dimensions: [],
    supported_windows: ["24h", "7d", "30d"],
    default_window: "24h",
    refresh_mode: "poll",
    refresh_interval_ms: 300000,
    value_shape: "scalar",
    unit: "count",
    precision: 0,
    evidence_mode: "none",
    stale_behavior: "show_last_with_warning",
    empty_behavior: "show_zero",
    error_behavior: "show_error_state",
    consumer_surfaces: ["analytics_engine"],
    placement_tags: ["secondary"],
    quality_tier: "high",
    status: "active",
  },
  {
    card_id: "maintenance_executions_24h_card",
    card_version: "1.0.0",
    title: "Maintenance Executions",
    subtitle: "Last 24 hours",
    description: "Number of maintenance task executions in the last 24 hours.",
    domain_id: "maintenance",
    category: "stat",
    visualization: "single_value",
    source_kind: "metric",
    metric_key: "maintenance.executions.count.24h",
    required_dimensions: [],
    optional_dimensions: ["maintenance_mode_id"],
    supported_windows: ["24h", "7d", "30d"],
    default_window: "24h",
    refresh_mode: "poll",
    refresh_interval_ms: 300000,
    value_shape: "scalar",
    unit: "count",
    precision: 0,
    evidence_mode: "none",
    stale_behavior: "show_last_with_warning",
    empty_behavior: "show_zero",
    error_behavior: "show_error_state",
    consumer_surfaces: ["analytics_engine", "maintenance_page"],
    placement_tags: ["secondary"],
    quality_tier: "high",
    status: "active",
  },
  {
    card_id: "verification_pass_rate_24h_card",
    card_version: "1.0.0",
    title: "Verification Pass Rate",
    subtitle: "Last 24 hours",
    description: "Percentage of verification checks that passed in the last 24 hours.",
    domain_id: "verification",
    category: "stat",
    visualization: "single_value",
    source_kind: "metric",
    metric_key: "verification.pass.rate.24h",
    required_dimensions: [],
    optional_dimensions: [],
    supported_windows: ["24h", "7d", "30d"],
    default_window: "24h",
    refresh_mode: "poll",
    refresh_interval_ms: 300000,
    value_shape: "scalar",
    unit: "percent",
    precision: 1,
    evidence_mode: "summary",
    stale_behavior: "show_last_with_warning",
    empty_behavior: "show_not_applicable",
    error_behavior: "show_error_state",
    consumer_surfaces: ["analytics_engine"],
    placement_tags: ["secondary"],
    quality_tier: "high",
    status: "active",
  },
  {
    card_id: "cost_tokens_24h_card",
    card_version: "1.0.0",
    title: "Token Usage",
    subtitle: "Last 24 hours",
    description: "Total tokens consumed across all operations in the last 24 hours.",
    domain_id: "cost_resources",
    category: "stat",
    visualization: "single_value",
    source_kind: "metric",
    metric_key: "cost.tokens.total.24h",
    required_dimensions: [],
    optional_dimensions: [],
    supported_windows: ["24h", "7d", "30d"],
    default_window: "24h",
    refresh_mode: "poll",
    refresh_interval_ms: 300000,
    value_shape: "scalar",
    unit: "tokens",
    precision: 0,
    evidence_mode: "none",
    stale_behavior: "show_last_with_warning",
    empty_behavior: "show_zero",
    error_behavior: "show_error_state",
    consumer_surfaces: ["analytics_engine"],
    placement_tags: ["secondary"],
    quality_tier: "high",
    status: "active",
  },
];

export function getMetricDefinition(metricKey: string): MetricDefinition | undefined {
  return METRIC_REGISTRY.find((m) => m.metric_key === metricKey);
}

export function getCardDefinition(cardId: string): CardDefinition | undefined {
  return CARD_REGISTRY.find((c) => c.card_id === cardId);
}

export function getCardsByDomain(domainId: string): CardDefinition[] {
  return CARD_REGISTRY.filter((c) => c.domain_id === domainId && c.status === "active");
}

export function getCardsBySurface(surface: string): CardDefinition[] {
  return CARD_REGISTRY.filter((c) => c.consumer_surfaces.includes(surface) && c.status === "active");
}
