#!/usr/bin/env node
/**
 * AXION Package
 * 
 * Bundles outputs into Agent Kit with different modes:
 * - docs: Locked documentation only
 * - scaffold: Docs + scaffold-app skeleton
 * - full: Docs + complete application code
 * 
 * Usage:
 *   node --import tsx axion/scripts/axion-package.ts --mode docs
 *   node --import tsx axion/scripts/axion-package.ts --mode full --app-path ./axion-app
 */

import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import archiver from 'archiver';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

let AXION_ROOT = process.env.AXION_WORKSPACE || path.join(process.cwd(), 'axion');
let REGISTRY_PATH = path.join(AXION_ROOT, 'registry');
let DOMAINS_PATH = path.join(AXION_ROOT, 'domains');
let CONFIG_PATH = path.join(AXION_ROOT, 'config');

type PackageMode = 'docs' | 'scaffold' | 'full';

interface PackageResult {
  status: 'success' | 'failed';
  stage: string;
  mode: PackageMode;
  output_path?: string;
  files_included?: number;
  zip_size_bytes?: number;
  zip_sha256?: string;
  hint?: string[];
}

interface ManifestEntry {
  path: string;
  size: number;
  sha256: string;
}

interface AgentKitManifest {
  version: string;
  created_at: string;
  mode: PackageMode;
  files: ManifestEntry[];
  locked_modules: string[];
  stack_profile?: string;
}

function sha256(data: Buffer | string): string {
  return crypto.createHash('sha256').update(data).digest('hex');
}

function walkDir(dir: string, basePath: string = ''): string[] {
  const files: string[] = [];
  
  if (!fs.existsSync(dir)) return files;
  
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    const relativePath = path.join(basePath, entry.name);
    
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === '.git') continue;
      files.push(...walkDir(fullPath, relativePath));
    } else {
      files.push(relativePath);
    }
  }
  
  return files;
}

function getLockedModules(): string[] {
  const lockManifestPath = path.join(REGISTRY_PATH, 'lock_manifest.json');
  
  if (fs.existsSync(lockManifestPath)) {
    try {
      const manifest = JSON.parse(fs.readFileSync(lockManifestPath, 'utf-8'));
      return manifest.modules || [];
    } catch {
      // Fall through to directory scan
    }
  }
  
  if (!fs.existsSync(DOMAINS_PATH)) return [];
  
  return fs.readdirSync(DOMAINS_PATH, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);
}

function generateAgentPrompt(mode: PackageMode, modules: string[]): string {
  let prompt = `# AXION Agent Kit\n\n`;
  prompt += `This kit was generated by AXION in **${mode}** mode.\n\n`;
  
  prompt += `## Locked Modules\n`;
  for (const module of modules) {
    prompt += `- ${module}\n`;
  }
  prompt += `\n`;
  
  prompt += `## Instructions\n\n`;
  
  if (mode === 'docs') {
    prompt += `This kit contains documentation only. Use these docs to:\n`;
    prompt += `1. Understand the system architecture (architecture/README.md)\n`;
    prompt += `2. Implement API contracts (contracts/README.md)\n`;
    prompt += `3. Create database schema (database/README.md)\n`;
    prompt += `4. Build frontend (frontend/README.md)\n`;
    prompt += `5. Follow all module specifications strictly\n`;
  } else if (mode === 'scaffold') {
    prompt += `This kit contains documentation and a scaffolded application.\n`;
    prompt += `1. Review the docs in domains/\n`;
    prompt += `2. The app skeleton is in app/\n`;
    prompt += `3. Implement features based on locked documentation\n`;
    prompt += `4. Do not invent features not in docs\n`;
  } else {
    prompt += `This kit contains documentation and a complete application.\n`;
    prompt += `1. Review the docs in domains/\n`;
    prompt += `2. The full application is in app/\n`;
    prompt += `3. Run tests to verify implementation\n`;
    prompt += `4. Deploy using the devops module guidelines\n`;
  }
  
  prompt += `\n## Key Rules\n`;
  prompt += `- Do NOT invent features not documented\n`;
  prompt += `- Follow the stack profile in architecture module\n`;
  prompt += `- Use error model from contracts module\n`;
  prompt += `- Mark any unknowns with UNKNOWN placeholder\n`;
  
  return prompt;
}

async function createZip(
  outputPath: string,
  mode: PackageMode,
  appPath: string | null
): Promise<{ files: ManifestEntry[]; size: number; hash: string }> {
  const files: ManifestEntry[] = [];
  
  return new Promise((resolve, reject) => {
    const output = fs.createWriteStream(outputPath);
    const archive = archiver('zip', { zlib: { level: 9 } });
    
    output.on('close', () => {
      const zipBuffer = fs.readFileSync(outputPath);
      resolve({
        files,
        size: archive.pointer(),
        hash: sha256(zipBuffer),
      });
    });
    
    archive.on('error', reject);
    archive.pipe(output);
    
    if (fs.existsSync(DOMAINS_PATH)) {
      const domainFiles = walkDir(DOMAINS_PATH);
      for (const file of domainFiles) {
        const fullPath = path.join(DOMAINS_PATH, file);
        const content = fs.readFileSync(fullPath);
        const archivePath = `domains/${file}`;
        
        archive.append(content, { name: archivePath });
        files.push({
          path: archivePath,
          size: content.length,
          sha256: sha256(content),
        });
      }
    }
    
    if (fs.existsSync(REGISTRY_PATH)) {
      const registryFiles = ['verify_report.json', 'lock_manifest.json', 'stage_markers.json']
        .filter(f => fs.existsSync(path.join(REGISTRY_PATH, f)));
      
      for (const file of registryFiles) {
        const fullPath = path.join(REGISTRY_PATH, file);
        const content = fs.readFileSync(fullPath);
        const archivePath = `registry/${file}`;
        
        archive.append(content, { name: archivePath });
        files.push({
          path: archivePath,
          size: content.length,
          sha256: sha256(content),
        });
      }
    }
    
    if (fs.existsSync(CONFIG_PATH)) {
      const configFiles = ['domains.json', 'presets.json', 'stack_profiles.json']
        .filter(f => fs.existsSync(path.join(CONFIG_PATH, f)));
      
      for (const file of configFiles) {
        const fullPath = path.join(CONFIG_PATH, file);
        const content = fs.readFileSync(fullPath);
        const archivePath = `config/${file}`;
        
        archive.append(content, { name: archivePath });
        files.push({
          path: archivePath,
          size: content.length,
          sha256: sha256(content),
        });
      }
    }
    
    if ((mode === 'scaffold' || mode === 'full') && appPath && fs.existsSync(appPath)) {
      const appFiles = walkDir(appPath);
      for (const file of appFiles) {
        const fullPath = path.join(appPath, file);
        const content = fs.readFileSync(fullPath);
        const archivePath = `app/${file}`;
        
        archive.append(content, { name: archivePath });
        files.push({
          path: archivePath,
          size: content.length,
          sha256: sha256(content),
        });
      }
    }
    
    const modules = getLockedModules();
    const agentPrompt = generateAgentPrompt(mode, modules);
    archive.append(agentPrompt, { name: 'AGENT_PROMPT.md' });
    files.push({
      path: 'AGENT_PROMPT.md',
      size: Buffer.byteLength(agentPrompt),
      sha256: sha256(agentPrompt),
    });
    
    const manifest: AgentKitManifest = {
      version: '2.0',
      created_at: new Date().toISOString(),
      mode,
      files: files.map(f => ({ path: f.path, size: f.size, sha256: f.sha256 })),
      locked_modules: modules,
    };
    
    const manifestJson = JSON.stringify(manifest, null, 2);
    archive.append(manifestJson, { name: 'manifest.json' });
    files.push({
      path: 'manifest.json',
      size: Buffer.byteLength(manifestJson),
      sha256: sha256(manifestJson),
    });
    
    archive.finalize();
  });
}

async function main() {
  const args = process.argv.slice(2);
  const modeIdx = args.indexOf('--mode');
  const appPathIdx = args.indexOf('--app-path');
  const outputIdx = args.indexOf('--output');
  const buildRootIdx = args.indexOf('--build-root');
  const projectNameIdx = args.indexOf('--project-name');
  
  const buildRoot = buildRootIdx !== -1 ? args[buildRootIdx + 1] : null;
  const projectName = projectNameIdx !== -1 ? args[projectNameIdx + 1] : null;
  
  // --build-root points to workspace root (e.g. workspaces/<project>)
  if (buildRoot) {
    AXION_ROOT = path.join(buildRoot, 'axion');
    REGISTRY_PATH = path.join(AXION_ROOT, 'registry');
    DOMAINS_PATH = path.join(AXION_ROOT, 'domains');
    CONFIG_PATH = path.join(AXION_ROOT, 'config');
  }
  
  let mode: PackageMode = modeIdx !== -1 
    ? (args[modeIdx + 1] as PackageMode) 
    : 'full';
  
  let appPath = appPathIdx !== -1 ? args[appPathIdx + 1] : null;
  
  const outputDir = outputIdx !== -1 
    ? args[outputIdx + 1] 
    : path.join(buildRoot || AXION_ROOT, 'dist');
  
  console.log('\n[AXION] Package\n');
  if (buildRoot) console.log(`[INFO] Workspace: ${buildRoot}`);
  console.log(`Mode: ${mode}`);
  
  if (!['docs', 'scaffold', 'full'].includes(mode)) {
    const result: PackageResult = {
      status: 'failed',
      stage: 'package',
      mode,
      hint: ['Invalid mode. Use: docs, scaffold, or full'],
    };
    console.log(JSON.stringify(result, null, 2));
    process.exit(1);
  }
  
  if (mode !== 'docs' && !appPath) {
    const candidates = buildRoot
      ? [path.join(buildRoot, 'app'), path.join(buildRoot, 'axion-app')]
      : [path.join(process.cwd(), 'axion-app'), path.join(process.cwd(), 'app')];
    
    for (const candidate of candidates) {
      if (fs.existsSync(candidate)) {
        appPath = candidate;
        break;
      }
    }
    
    if (!appPath) {
      console.log(`[WARN] No app path found for ${mode} mode, falling back to docs mode`);
      mode = 'docs';
    }
  }
  
  if (appPath) {
    console.log(`App: ${appPath}`);
  }
  
  fs.mkdirSync(outputDir, { recursive: true });
  
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const zipFilename = `agent_kit_${mode}_${timestamp}.zip`;
  const zipPath = path.join(outputDir, zipFilename);
  
  console.log(`Output: ${zipPath}`);
  console.log('');
  
  try {
    const { files, size, hash } = await createZip(zipPath, mode, appPath);
    
    console.log(`\n[SUCCESS] Created Agent Kit\n`);
    console.log(`Files: ${files.length}`);
    console.log(`Size: ${(size / 1024).toFixed(2)} KB`);
    console.log(`SHA256: ${hash.slice(0, 16)}...`);
    console.log('');
    
    const result: PackageResult = {
      status: 'success',
      stage: 'package',
      mode,
      output_path: zipPath,
      files_included: files.length,
      zip_size_bytes: size,
      zip_sha256: hash,
    };
    
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    const result: PackageResult = {
      status: 'failed',
      stage: 'package',
      mode,
      hint: [error instanceof Error ? error.message : 'Unknown error'],
    };
    console.log(JSON.stringify(result, null, 2));
    process.exit(1);
  }
}

main();
