import fs from "fs";
import path from "path";
import { generateAllDocs, type GenerateDocsOptions } from "./ai-generator";

const WORKSPACES_DIR = "workspaces";
const TEMPLATES_DIR = "docs/roshi_v2/01_templates";

export interface WorkspaceConfig {
  runId: string;
  projectName: string;
  idea: string;
  context?: string;
  domains: string[];
}

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function copyDir(src: string, dest: string) {
  ensureDir(dest);
  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

export async function createWorkspace(config: WorkspaceConfig): Promise<string> {
  const workspaceRoot = path.join(WORKSPACES_DIR, config.runId);
  const docsRoot = path.join(workspaceRoot, "docs/roshi_v2");
  
  ensureDir(workspaceRoot);
  ensureDir(docsRoot);
  ensureDir(path.join(docsRoot, "00_product"));
  ensureDir(path.join(docsRoot, "00_registry"));
  ensureDir(path.join(docsRoot, "01_templates"));
  ensureDir(path.join(docsRoot, "02_domains"));
  ensureDir(path.join(docsRoot, "03_workflows"));
  ensureDir(path.join(workspaceRoot, "roshi"));
  
  if (fs.existsSync(TEMPLATES_DIR)) {
    copyDir(TEMPLATES_DIR, path.join(docsRoot, "01_templates"));
  }
  
  const domainsConfig = {
    roshi_root: "docs/roshi_v2",
    domains_dir: "02_domains",
    templates_dir: "01_templates",
    domains: config.domains.map((slug, i) => ({
      name: slug.charAt(0).toUpperCase() + slug.slice(1).replace(/-/g, " "),
      slug: slug,
      prefix: slug.replace(/-/g, "_"),
      type: i === 0 ? "business" : "crosscutting"
    }))
  };
  
  fs.writeFileSync(
    path.join(workspaceRoot, "roshi/domains.json"),
    JSON.stringify(domainsConfig, null, 2)
  );
  
  const sourcesConfig = {
    roshi_root: "docs/roshi_v2",
    sources: [
      "00_product/RPBS_Product.md",
      "00_product/REBS_Product.md",
      "00_product/PROJECT_OVERVIEW.md",
      "00_registry/domain-map.md",
      "00_registry/reason-codes.md",
      "00_registry/action-vocabulary.md",
      "00_registry/glossary.md"
    ],
    domain_notes: {
      enabled: false,
      dir: "notes/domains",
      pattern: "{slug}.md"
    },
    sourceref: {
      required: true,
      format: "HeadingPath",
      example: "RPBS > Hard Rules Catalog > Feature"
    }
  };
  
  fs.writeFileSync(
    path.join(workspaceRoot, "roshi/sources.json"),
    JSON.stringify(sourcesConfig, null, 2)
  );
  
  console.log(`[Workspace] Created workspace structure for run ${config.runId}`);
  
  return workspaceRoot;
}

export async function populateWorkspaceWithAI(config: WorkspaceConfig, workspaceRoot: string): Promise<void> {
  const docsRoot = path.join(workspaceRoot, "docs/roshi_v2");
  
  console.log(`[AI] Generating documentation for "${config.projectName || config.idea.substring(0, 50)}..."`);
  
  const genOptions: GenerateDocsOptions = {
    idea: config.idea,
    projectName: config.projectName,
    context: config.context,
    domains: config.domains,
  };
  
  const docs = await generateAllDocs(genOptions);
  
  fs.writeFileSync(
    path.join(docsRoot, "00_product/PROJECT_OVERVIEW.md"),
    docs.projectOverview
  );
  
  fs.writeFileSync(
    path.join(docsRoot, "00_product/RPBS_Product.md"),
    docs.rpbs
  );
  
  fs.writeFileSync(
    path.join(docsRoot, "00_product/REBS_Product.md"),
    docs.rebs
  );
  
  fs.writeFileSync(
    path.join(docsRoot, "00_registry/domain-map.md"),
    docs.domainMap
  );
  
  fs.writeFileSync(
    path.join(docsRoot, "00_registry/reason-codes.md"),
    docs.reasonCodes
  );
  
  fs.writeFileSync(
    path.join(docsRoot, "00_registry/action-vocabulary.md"),
    docs.actionVocabulary
  );
  
  fs.writeFileSync(
    path.join(docsRoot, "00_registry/glossary.md"),
    docs.glossary
  );
  
  const readme = `# ${config.projectName || "Project"} - Roshi Documentation

Generated by Roshi Studio from idea:
> ${config.idea}

## Structure

- \`00_product/\` - Product and engineering specifications
  - PROJECT_OVERVIEW.md - Project summary
  - RPBS_Product.md - Product requirements
  - REBS_Product.md - Engineering specifications
- \`00_registry/\` - Shared definitions
  - domain-map.md - Domain boundaries
  - reason-codes.md - Error code catalog
  - action-vocabulary.md - Standardized actions
  - glossary.md - Term definitions
- \`01_templates/\` - Domain doc templates
- \`02_domains/\` - Per-domain documentation (generated by pipeline)
- \`03_workflows/\` - Workflow documentation

## Next Steps

1. Review generated documentation
2. Run \`npm run roshi:gen\` to generate domain packs
3. Run \`npm run roshi:seed\` to seed starter content
4. Run \`npm run roshi:draft\` to extract truth from sources
5. Resolve any UNKNOWN items
6. Run \`npm run roshi:verify\` to validate
7. Run \`npm run roshi:lock\` to finalize

## Domains

${config.domains.map(d => `- ${d}`).join("\n")}
`;
  
  fs.writeFileSync(path.join(docsRoot, "README.md"), readme);
  
  console.log(`[AI] Generated ${Object.keys(docs).length} source documents`);
}

export function getWorkspacePath(runId: string): string {
  return path.join(WORKSPACES_DIR, runId);
}

export function workspaceExists(runId: string): boolean {
  return fs.existsSync(getWorkspacePath(runId));
}

export function cleanupWorkspace(runId: string): void {
  const workspacePath = getWorkspacePath(runId);
  if (fs.existsSync(workspacePath)) {
    fs.rmSync(workspacePath, { recursive: true, force: true });
  }
}
