import type { AVCSTestDefinition, AVCSTestDomain, CertificationRunType } from "./types.js";

export const TEST_CATALOG: AVCSTestDefinition[] = [
  {
    id: "BI-01",
    domain: "BUILD_INTEGRITY",
    name: "Artifact Location Exists",
    description: "Verify the build artifact directory exists and is readable.",
    phase: "MVP",
    primaryTools: ["internal"],
    runTypes: ["smoke", "functional", "security", "performance", "full_certification", "pre_deployment"],
    evidenceOutput: "filesystem result, summary",
    failExamples: ["artifact path invalid", "directory unreadable"],
  },
  {
    id: "BI-02",
    domain: "BUILD_INTEGRITY",
    name: "Required Files Present",
    description: "Verify critical build files exist (package.json, lock files, configuration files).",
    phase: "MVP",
    primaryTools: ["internal"],
    runTypes: ["smoke", "functional", "security", "performance", "full_certification", "pre_deployment"],
    evidenceOutput: "file check result, summary",
    failExamples: ["missing required file", "corrupted file"],
  },
  {
    id: "BI-03",
    domain: "BUILD_INTEGRITY",
    name: "Environment Contract Exists",
    description: "Ensure environment variable requirements are documented (.env.example, env.contract.json, .env.schema.json).",
    phase: "MVP",
    primaryTools: ["internal"],
    runTypes: ["smoke", "functional", "security", "performance", "full_certification", "pre_deployment"],
    evidenceOutput: "config/file check result",
    failExamples: ["env contract missing", "env variables undocumented"],
  },
  {
    id: "BI-04",
    domain: "BUILD_INTEGRITY",
    name: "Startup Script Declared",
    description: "Verify the system has a startup path (npm start, npm run dev, npm run build).",
    phase: "MVP",
    primaryTools: ["internal"],
    runTypes: ["smoke", "functional", "security", "performance", "full_certification", "pre_deployment"],
    evidenceOutput: "parsed package/config result",
    failExamples: ["startup script missing", "startup path invalid"],
  },
  {
    id: "BI-05",
    domain: "BUILD_INTEGRITY",
    name: "Build Output Readable",
    description: "Ensure the artifact output can be accessed without permission issues.",
    phase: "Later",
    primaryTools: ["internal"],
    runTypes: ["smoke", "functional", "security", "performance", "full_certification", "pre_deployment"],
    evidenceOutput: "filesystem/permission result",
    failExamples: ["permissions block access", "corrupted build output"],
  },

  {
    id: "FUNC-01",
    domain: "FUNCTIONAL",
    name: "Primary Workflow Executes",
    description: "Verify the main user workflow completes successfully (Create → Save → View).",
    phase: "MVP",
    primaryTools: ["playwright", "internal"],
    runTypes: ["smoke", "functional", "full_certification", "pre_deployment"],
    evidenceOutput: "run log, screenshots, flow result",
    failExamples: ["workflow crashes", "state transition fails"],
  },
  {
    id: "FUNC-02",
    domain: "FUNCTIONAL",
    name: "API Contract Valid",
    description: "Ensure API responses match expected schema.",
    phase: "MVP",
    primaryTools: ["playwright", "internal"],
    runTypes: ["functional", "full_certification", "pre_deployment"],
    evidenceOutput: "request/response capture, assertion result",
    failExamples: ["missing required response fields", "invalid response format"],
  },
  {
    id: "FUNC-03",
    domain: "FUNCTIONAL",
    name: "CRUD Operations Work",
    description: "Verify create, read, update, delete operations.",
    phase: "MVP",
    primaryTools: ["playwright", "internal"],
    runTypes: ["functional", "full_certification", "pre_deployment"],
    evidenceOutput: "flow log, screenshots, state result",
    failExamples: ["data not persisted", "operation silently fails"],
  },
  {
    id: "FUNC-04",
    domain: "FUNCTIONAL",
    name: "Error Handling Path Works",
    description: "Verify the system handles invalid input properly.",
    phase: "MVP",
    primaryTools: ["playwright", "internal"],
    runTypes: ["functional", "full_certification", "pre_deployment"],
    evidenceOutput: "error-state screenshots, logs",
    failExamples: ["unhandled exception", "silent error"],
  },
  {
    id: "FUNC-05",
    domain: "FUNCTIONAL",
    name: "State Transition Integrity",
    description: "Verify system states change correctly (draft → active, pending → approved).",
    phase: "Later",
    primaryTools: ["playwright", "internal"],
    runTypes: ["functional", "full_certification", "pre_deployment"],
    evidenceOutput: "state transition records",
    failExamples: ["illegal transition", "stuck state"],
  },

  {
    id: "SEC-01",
    domain: "SECURITY",
    name: "Dependency Vulnerability Scan",
    description: "Detect known vulnerable dependencies.",
    phase: "MVP",
    primaryTools: ["trivy", "internal"],
    runTypes: ["security", "full_certification", "pre_deployment"],
    evidenceOutput: "scan reports, CVE results",
    failExamples: ["critical CVE detected"],
  },
  {
    id: "SEC-02",
    domain: "SECURITY",
    name: "Secrets Exposure Scan",
    description: "Detect exposed secrets (API keys, credentials in code).",
    phase: "MVP",
    primaryTools: ["trivy", "internal"],
    runTypes: ["security", "full_certification", "pre_deployment"],
    evidenceOutput: "secret scan report",
    failExamples: ["API keys in code", "credentials in config"],
  },
  {
    id: "SEC-03",
    domain: "SECURITY",
    name: "Authentication Boundary Check",
    description: "Ensure protected routes require authentication.",
    phase: "Later",
    primaryTools: ["zap", "playwright"],
    runTypes: ["security", "full_certification", "pre_deployment"],
    evidenceOutput: "auth test result, findings, traces",
    failExamples: ["unauthorized access possible"],
  },
  {
    id: "SEC-04",
    domain: "SECURITY",
    name: "Permission Enforcement",
    description: "Ensure roles cannot access unauthorized resources.",
    phase: "Later",
    primaryTools: ["zap", "playwright"],
    runTypes: ["security", "full_certification", "pre_deployment"],
    evidenceOutput: "permission test result, findings",
    failExamples: ["role escalation", "permission bypass"],
  },
  {
    id: "SEC-05",
    domain: "SECURITY",
    name: "Unsafe Config Exposure",
    description: "Detect exposed debug or admin surfaces.",
    phase: "MVP",
    primaryTools: ["trivy", "semgrep", "zap", "internal"],
    runTypes: ["security", "full_certification", "pre_deployment"],
    evidenceOutput: "scan report, config findings",
    failExamples: ["debug endpoints exposed", "dev configs in production"],
  },

  {
    id: "PERF-01",
    domain: "PERFORMANCE",
    name: "Startup Time",
    description: "Measure application startup latency.",
    phase: "MVP",
    primaryTools: ["lighthouse", "internal"],
    runTypes: ["performance", "full_certification", "pre_deployment"],
    evidenceOutput: "audit JSON, score, timings",
    failExamples: ["startup exceeds threshold"],
  },
  {
    id: "PERF-02",
    domain: "PERFORMANCE",
    name: "Route Load Time",
    description: "Measure page or API load latency.",
    phase: "MVP",
    primaryTools: ["lighthouse", "internal"],
    runTypes: ["performance", "full_certification", "pre_deployment"],
    evidenceOutput: "audit JSON, route timings",
    failExamples: ["route latency exceeds threshold"],
  },
  {
    id: "PERF-03",
    domain: "PERFORMANCE",
    name: "Repeated Action Stability",
    description: "Ensure repeated operations remain stable (repeat action 100 times).",
    phase: "MVP",
    primaryTools: ["k6", "playwright", "internal"],
    runTypes: ["performance", "full_certification", "pre_deployment"],
    evidenceOutput: "load metrics, stability logs",
    failExamples: ["performance degradation", "memory leak"],
  },
  {
    id: "PERF-04",
    domain: "PERFORMANCE",
    name: "Resource Budget Check",
    description: "Verify resource usage stays within limits (bundle size, memory).",
    phase: "Later",
    primaryTools: ["lighthouse"],
    runTypes: ["performance", "full_certification"],
    evidenceOutput: "bundle/resource audit",
    failExamples: ["bundle size too large", "excessive memory usage"],
  },
  {
    id: "PERF-05",
    domain: "PERFORMANCE",
    name: "Concurrency Stability",
    description: "Verify system stability under concurrent users.",
    phase: "Later",
    primaryTools: ["k6"],
    runTypes: ["performance", "full_certification"],
    evidenceOutput: "load report, latency/error metrics",
    failExamples: ["race conditions", "crashes under load"],
  },

  {
    id: "DEP-01",
    domain: "DEPLOYMENT",
    name: "Environment Variables Declared",
    description: "Verify required environment variables are defined.",
    phase: "MVP",
    primaryTools: ["internal"],
    runTypes: ["smoke", "full_certification", "pre_deployment"],
    evidenceOutput: "env contract check result",
    failExamples: ["missing required variable"],
  },
  {
    id: "DEP-02",
    domain: "DEPLOYMENT",
    name: "Startup Path Works",
    description: "Verify the application starts successfully.",
    phase: "MVP",
    primaryTools: ["internal"],
    runTypes: ["smoke", "full_certification", "pre_deployment"],
    evidenceOutput: "startup execution log",
    failExamples: ["runtime startup failure"],
  },
  {
    id: "DEP-03",
    domain: "DEPLOYMENT",
    name: "Health Endpoint Exists",
    description: "Ensure readiness or health endpoint exists.",
    phase: "MVP",
    primaryTools: ["internal"],
    runTypes: ["smoke", "full_certification", "pre_deployment"],
    evidenceOutput: "endpoint probe result",
    failExamples: ["missing health check"],
  },
  {
    id: "DEP-04",
    domain: "DEPLOYMENT",
    name: "Deployment Config Present",
    description: "Verify deployment configuration exists (Dockerfile, deployment config).",
    phase: "Later",
    primaryTools: ["internal", "trivy"],
    runTypes: ["full_certification", "pre_deployment"],
    evidenceOutput: "config check, scan result",
    failExamples: ["deployment undefined"],
  },

  {
    id: "UI-01",
    domain: "UI",
    name: "Layout Render Integrity",
    description: "Verify UI layout renders correctly.",
    phase: "Later",
    primaryTools: ["playwright", "backstop"],
    runTypes: ["full_certification"],
    evidenceOutput: "screenshots, visual diff",
    failExamples: ["overlapping UI", "broken layout"],
  },
  {
    id: "UI-02",
    domain: "UI",
    name: "Responsive Layout Check",
    description: "Verify responsive behavior works across viewports.",
    phase: "Later",
    primaryTools: ["playwright", "backstop"],
    runTypes: ["full_certification"],
    evidenceOutput: "viewport screenshots, diffs",
    failExamples: ["mobile layout broken"],
  },
  {
    id: "UI-03",
    domain: "UI",
    name: "Visual Regression Detection",
    description: "Detect unintended visual changes.",
    phase: "Later",
    primaryTools: ["backstop"],
    runTypes: ["full_certification"],
    evidenceOutput: "baseline diff report",
    failExamples: ["screenshot mismatch"],
  },

  {
    id: "UX-01",
    domain: "UX",
    name: "Workflow Completion Path",
    description: "Verify workflows can be completed end-to-end.",
    phase: "Later",
    primaryTools: ["playwright"],
    runTypes: ["full_certification"],
    evidenceOutput: "flow result, screenshots",
    failExamples: ["dead-end navigation"],
  },
  {
    id: "UX-02",
    domain: "UX",
    name: "Error Recovery Path",
    description: "Ensure users can recover from errors.",
    phase: "Later",
    primaryTools: ["playwright"],
    runTypes: ["full_certification"],
    evidenceOutput: "recovery flow log, screenshots",
    failExamples: ["no recovery option"],
  },
  {
    id: "UX-03",
    domain: "UX",
    name: "Empty State Actionability",
    description: "Ensure empty states guide the user with clear actions.",
    phase: "Later",
    primaryTools: ["playwright"],
    runTypes: ["full_certification"],
    evidenceOutput: "state screenshot, flow result",
    failExamples: ["empty state with no action"],
  },

  {
    id: "ACC-01",
    domain: "ACCESSIBILITY",
    name: "Keyboard Navigation",
    description: "Ensure UI can be navigated via keyboard.",
    phase: "Later",
    primaryTools: ["axe", "playwright"],
    runTypes: ["full_certification"],
    evidenceOutput: "accessibility report, flow result",
    failExamples: ["unreachable controls"],
  },
  {
    id: "ACC-02",
    domain: "ACCESSIBILITY",
    name: "Focus Visibility",
    description: "Ensure focus indicators are visible.",
    phase: "Later",
    primaryTools: ["axe", "playwright"],
    runTypes: ["full_certification"],
    evidenceOutput: "accessibility report, screenshots",
    failExamples: ["hidden focus state"],
  },
  {
    id: "ACC-03",
    domain: "ACCESSIBILITY",
    name: "Accessible Labels",
    description: "Ensure form controls have labels.",
    phase: "Later",
    primaryTools: ["axe"],
    runTypes: ["full_certification"],
    evidenceOutput: "accessibility report",
    failExamples: ["unlabeled inputs"],
  },
  {
    id: "ACC-04",
    domain: "ACCESSIBILITY",
    name: "Color Contrast",
    description: "Ensure readable UI contrast ratios.",
    phase: "Later",
    primaryTools: ["axe", "lighthouse"],
    runTypes: ["full_certification"],
    evidenceOutput: "accessibility report, audit result",
    failExamples: ["low contrast on critical text"],
  },

  {
    id: "ENT-01",
    domain: "ENTERPRISE",
    name: "Audit Trail Presence",
    description: "Verify critical actions are recorded in an audit trail.",
    phase: "Later",
    primaryTools: ["internal"],
    runTypes: ["full_certification", "pre_deployment"],
    evidenceOutput: "audit/log validation result",
    failExamples: ["action not logged"],
  },
  {
    id: "ENT-02",
    domain: "ENTERPRISE",
    name: "Structured Logging",
    description: "Ensure logs are structured and usable.",
    phase: "Later",
    primaryTools: ["internal"],
    runTypes: ["full_certification", "pre_deployment"],
    evidenceOutput: "log-shape validation result",
    failExamples: ["missing context", "unstructured logs"],
  },
  {
    id: "ENT-03",
    domain: "ENTERPRISE",
    name: "Observability Signals",
    description: "Ensure system exposes monitoring signals (health metrics, telemetry).",
    phase: "Later",
    primaryTools: ["internal"],
    runTypes: ["full_certification", "pre_deployment"],
    evidenceOutput: "health/metrics validation result",
    failExamples: ["no health metrics", "no telemetry"],
  },
];

export function getTestById(testId: string): AVCSTestDefinition | undefined {
  return TEST_CATALOG.find(t => t.id === testId);
}

export function getTestsByDomain(domain: AVCSTestDomain): AVCSTestDefinition[] {
  return TEST_CATALOG.filter(t => t.domain === domain);
}

export function getMVPTests(): AVCSTestDefinition[] {
  return TEST_CATALOG.filter(t => t.phase === "MVP");
}

export function getTestsByRunType(runType: CertificationRunType): AVCSTestDefinition[] {
  return TEST_CATALOG.filter(t => t.runTypes.includes(runType));
}

export function getTestsByTool(toolId: string): AVCSTestDefinition[] {
  return TEST_CATALOG.filter(t => t.primaryTools.includes(toolId));
}

